### ISSUE TITLE
Add a tracking for analytics in the API for OMNA LwM2M API

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LWM2M_Editor#46]
- [ ] Move Joaquin's Google Analytics to his address
- [ ]  Statistics are available in ```Events/Overview```
- [ ] What role is played by CloudFlare? It catchs some of the traffic
  * Do we see all the traffic? No.
-

**Comment by SvanteAlnas** [comment]
Done in separate GA account that you have access to
